---
title: A Raspberry Pi laser tripwire
hero_image: images/banner.png
description: Build a laser tripwire with Python and a Raspberry Pi
original_url: https://www.raspberrypi.org/learning/laser-tripwire/
theme: cc-prototype
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-2, phys-comp-3, manufacture-1, community-0
interests: humour
technologies: raspberry-pi, python, electronic-components
hardware: raspberry-pi, electronic-components
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps:
- title: What you will make
- title: Detecting a broken beam
  completion:
  - engaged
- title: Making some noise
  completion:
  - internal
- title: Building your laser tripwire
  completion:
  - external
- title: Challenge
  challenge: true
- title: What can you do now?
